version: '3.7'

services:
  server:
    image: gegedesembri/blynk-server:latest
    environment:
      INITIAL_ENERGY: "100000"
      ADMIN_EMAIL: "admin@mail.com"
      ADMIN_PASS: "admin12345"
    volumes:
      - blynk-config:/blynk/config
      - blynk-data:/blynk/data/backup
    ports:
      - "8440:8440"
      - "8080:8080"
      - "9443:9443"

volumes:
  blynk-config:
  blynk-data:
