version: '3.7'

services:
  server:
    image: gegedesembri/telegram-bot-api:0.1
    environment:
      TELEGRAM_API_ID: "API_ID"
      TELEGRAM_API_HASH: "API_HASH"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"

volumes:
  telegram-bot-api-data:
